package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "heap_sort",
  srcs = ["heap_sort.cc"],
  # hdrs = ["header files"],
  deps = ["@glog"],
)

# cc_test(
#   name = ""
# )
