package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sorting_test_base",
    # srcs = ["sorting"],
    hdrs = ["sorting_test_base.h"],
    deps = [
        "@gtest",
    ],
)

# cc_test(
#     name = "heap_sort_test",
#     srcs = ["heap_sort_test.cc"],
#     deps = [
#         "//books:heap_sort",
#         ":sorting_test_base",
#         "@gtest",
#         "@gtest//:gtest_main",
#     ],
# )

# cc_test(
#     name = "quick_sort_test",
#     srcs = ["quick_sort_test.cc"],
#     deps = [
#         "//books:quick_sort",
#         ":sorting_test_base",
#         "@gtest",
#         "@gtest//:gtest_main",
#     ],
# )

