package(default_visibility = ["//visibility:public"])

cc_test(
    name = "heap_sort_test",
    srcs = ["heap_sort_test.cc"],
    deps = [
        "//books:heap_sort",
        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
)
